--- #YAML:1.0
name:                Class-Declare-Attributes
version:             0.06
abstract:            Class::Declare method types using Perl attributes.
license:             ~
author:              
    - Ian Brayshaw <ian@onemore.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Class::Declare:                0.06
    Test::Exception:               0.15
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
